#ifndef SOUNDBRIDGE_CONFIG_HPP
#define SOUNDBRIDGE_CONFIG_HPP

#ifndef SOUNDBRIDGE_ENABLE_GRAPHICS
#define SOUNDBRIDGE_ENABLE_GRAPHICS 0
#endif

#ifndef SOUNDBRIDGE_VERSION_PROYECTO
#define SOUNDBRIDGE_VERSION_PROYECTO "0.1.0"
#endif

namespace soundbridge {

inline constexpr const char* NOMBRE_PROYECTO = "SoundBridge";
inline constexpr const char* VERSION_PROYECTO = SOUNDBRIDGE_VERSION_PROYECTO;
inline constexpr bool SOPORTE_GRAFICO_HABILITADO = SOUNDBRIDGE_ENABLE_GRAPHICS != 0;

}

#endif
